### ISSUE TITLE
prefresher does not render online anymore

### ISSUE THREAD

**Issue by hugeme** [IQSS/prefresher#68]
Interacting with 
https://bookdown.org/kuriwaki/prefresher/ results in blank pages

**Comment by schwenzfeier** [comment]
A few months back we changed the url to: https://iqss.github.io/prefresher/

This one appears to be fine - let us know if you can't access it!

**Comment by kuriwaki** [comment]
@hugeme  - thanks, yes, please use the link above let us know if we can help further. We have also made it easier to get the PDF and TeX source (see [README](https://github.com/IQSS/prefresher)).
